version: '3'

services:
  overlay-server:
    container_name: overlay-server
    build: 
      context: ./overlay-server
    environment:
     - SERVERHOST=${SERVERHOST}
     - SERVERPORT=${SERVERPORT}
     - AUTHKEY=${AUTHKEY}
    ports:
     - "${SERVERPORT}:${SERVERPORT}"

  overlay-manager-api:
    container_name: overlay-manager-api
    build: 
      context: ./overlay-manager-api
    environment:
     - MANAGERAPIHOST=${MANAGERAPIHOST}
     - MANAGERAPIPORT=${MANAGERAPIPORT}
     - SERVERHOST=${SERVERHOST}
     - SERVERPORT=${SERVERPORT}
     - AUTHKEY=${AUTHKEY}
    ports:
     - "${MANAGERAPIPORT}:${MANAGERAPIPORT}"

  overlay-manager:
    container_name: overlay-manager
    build: 
      context: ./overlay-manager
    environment:
     - MANAGERHOST=${MANAGERHOST}
     - MANAGERPORT=${MANAGERPORT}
     - MANAGERAPIHOST=${MANAGERAPIHOST}
     - MANAGERAPIPORT=${MANAGERAPIPORT}
     - SERVERHOST=${SERVERHOST}
     - SERVERPORT=${SERVERPORT}
     - AUTHKEY=${AUTHKEY}
    ports:
     - "${MANAGERPORT}:80"