version: '3'

services:
  overlay-server:
    container_name: overlay-server
    image: "node:12"
    working_dir: /overlay-server
    command: bash -c "npm install && npm start"
    environment:
     - SERVERHOST=${SERVERHOST}
     - SERVERPORT=${SERVERPORT}
     - AUTHKEY=${AUTHKEY}
    ports:
     - "${SERVERPORT}:${SERVERPORT}"
    volumes:
     - ./overlay-server/:/overlay-server

  overlay-manager:
    image: nginx:alpine
    volumes:
      - ./overlay-manager/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./overlay-manager/dist/overlay-manager:/overlay-manager
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
     - "${MANAGERPORT}:80"
    depends_on:
      - "overlay-server"