version: '3'

services:
  overlay-server:
    container_name: overlay-server
    build: 
      context: ./overlay-server
    environment:
     - SERVERHOST=${SERVERHOST}
     - SERVERPORT=${SERVERPORT}
     - AUTHKEY=${AUTHKEY}
    ports:
     - "${SERVERPORT}:${SERVERPORT}"

  overlay-manager-api:
    container_name: overlay-manager-api
    build: 
      context: ./overlay-manager-api
    environment:
     - MANAGERHOST=${MANAGERHOST}
     - MANAGERPORT=${MANAGERPORT}
     - SERVERHOST=${SERVERHOST}
     - SERVERPORT=${SERVERPORT}
     - AUTHKEY=${AUTHKEY}
    ports:
     - "${MANAGERPORT}:${MANAGERPORT}"

  overlay-remote:
    container_name: overlay-remote
    build: 
      context: ./overlay-remote
    environment:
     - MANAGERHOST=${MANAGERHOST}
     - MANAGERPORT=${MANAGERPORT}
     - SERVERHOST=${SERVERHOST}
     - SERVERPORT=${SERVERPORT}
     - AUTHKEY=${AUTHKEY}